import numpy as np
import matplotlib.pyplot as plt

def apply_lms(primary_signal, reference_noise, mu=0.01, filter_order=32, fs=16000, show_plot=True, ideal_signal=None):
    """Core LMS Filter Function"""
    
    n_samples = min(len(primary_signal), len(reference_noise)) #takes the least number of samples
    primary_signal = primary_signal[0:n_samples] #crop to the minimum sample length
    reference_noise = reference_noise[0:n_samples] #crop
    
    w = np.zeros(filter_order) #generates matrix of weights (initialised to 0)
    clean_voice = np.zeros(n_samples) #generates empty matrix to store the output in 
    x_buffer = np.zeros(filter_order) #stores most recent "filter order"(defines number of weights and noise samples which affect the output) sample of noise
    
    # CORE MATH LOOP 
    for n in range(n_samples):
        x_buffer[1:] = x_buffer[:-1] #It moves all old samples one spot to the right and drops the oldest one.
        x_buffer[0] = reference_noise[n] #The newest noise sample is inserted at index 0.
        
        y = np.dot(w, x_buffer) #matrix multiplication of weights and noise
        e = primary_signal[n] - y #error signal generated by subtracting weighted noise from raw signal
        clean_voice[n] = e #clean voice is made = error
        
        w = w + mu * e * x_buffer #update w[n+1]=w[n]+mu*e[n]*x[n] MAIN LMS CONCEPT

    # PLOTTING LOGIC
    if show_plot:
        plot_samples = min(1000, n_samples) #plot maximum only 1000 samples just to showcase
        # Start looking from the 1.0 second mark to let the filter "settle" (immediate plot yielded 0) as few ms of 0 input is present in .wav file
        #also initial ms of output is messy as weights are distributed
        start_idx = min(int(7.0 * fs), n_samples - plot_samples) 
        #min of either 1s in or latest possible point which allows 1000 samples after it
        end_idx = start_idx + plot_samples 
        t = np.linspace(start_idx/fs, end_idx/fs, plot_samples, endpoint=False)
        #start t axis at start point n end at end point, number of points (number of points marked on axis), upto but not including last value thus endpoint = false

        # Decide how many rows based on if we have an ideal signal (for graph plotting)
        rows = 4 if ideal_signal is not None else 3
        plt.figure(figsize=(12, 10))
        
        curr_row = 1
        
        # 1. Pure Sine Wave (Ideal) - Only shows if passed to the function
        if ideal_signal is not None:
            plt.subplot(rows, 1, curr_row)
            plt.title("Clean sine wave (Expected Output)")
            plt.plot(t, ideal_signal[start_idx:end_idx], color='green', linewidth=2)
            plt.grid(True)
            curr_row += 1

        # 2. Noisy Input
        plt.subplot(rows, 1, curr_row)
        plt.title("Clean + Noise Audio")
        plt.plot(t, primary_signal[start_idx:end_idx], color='red', alpha=1) #alpha sets transparency of line 0 for invisible
        plt.grid(True) #adds grid in bg of graph
        curr_row += 1

        # 3. Reference Noise
        plt.subplot(rows, 1, curr_row)
        plt.title("Noise Only")
        plt.plot(t, reference_noise[start_idx:end_idx], color='gray')
        plt.grid(True)
        curr_row += 1

        # 4. Recovered Signal
        plt.subplot(rows, 1, curr_row)
        plt.title(f"LMS Filtered OutPut")
        plt.plot(t, clean_voice[start_idx:end_idx], color='blue', linewidth=2)
        plt.xlabel("Time (seconds)")
        plt.grid(True)
        
        plt.tight_layout() #fits everything in the window
        plt.show() #code pauses here till u close the window

        print(f"\n--- Filter Weight Stats ---")
        print(f"Max Weight Value: {np.max(np.abs(w))}")
        print(f"Mean Weight Value: {np.mean(w)}")

        # # 2. Plot the weights (The Impulse Response)
        # plt.figure(figsize=(10, 4))
        # plt.stem(w, markerfmt=' ', basefmt="r-")
        # plt.title("LMS Filter Weights (Impulse Response)")
        # plt.xlabel("Weight Index (Tap)")
        # plt.ylabel("Value")
        # plt.grid(True)
        # plt.show()

    return clean_voice